export const TECHNOLOGIES = [
  { name: "HTML5" },
  { name: "CSS3" },
  { name: "Bootstrap 5" },
  { name: "Material UI" },
  { name: "Responsive Design" },
  { name: "JavaScript" },
  { name: "React" },
  { name: "Vite" },
  { name: "Axios / Fetch" },
  { name: "Node.js" },
  { name: "Express.js" },
  { name: "RESTful APIs" },
  { name: "EJS Templating" },
  { name: "Python" },
  { name: "Django" },
  { name: "MongoDB" },
  { name: "Mongoose ODM" },
  { name: "Passport.js (Auth)" },
  { name: "JOI Validation" },
  { name: "Helmet.js (Security)" },
  { name: "Cloudinary (Image Upload)" },
  { name: "MapTiler (Maps)" },
  { name: "Git & Terminal" },
  { name: "Render / Heroku" },
];
